-- MySQL Script generated by MySQL Workbench
-- Fri Jul 15 01:01:45 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `barang`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `barang` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `barang` (
  `idbarang` INT NOT NULL AUTO_INCREMENT,
  `namaBarang` VARCHAR(255) NOT NULL,
  `stockBarang` INT NOT NULL,
  `hargajualBarang` INT NOT NULL,
  `hargabeliBarang` INT NOT NULL,
  `isDeleted` INT NOT NULL,
  `kategori_idkategori` INT NOT NULL,
  PRIMARY KEY (`idbarang`, `kategori_idkategori`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `kategori`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `kategori` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `kategori` (
  `idkategori` INT NOT NULL AUTO_INCREMENT,
  `nama` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idkategori`))
ENGINE = InnoDB;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `pembelian`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `pembelian` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `pembelian` (
  `idpembelian` INT NOT NULL AUTO_INCREMENT,
  `namaPembeli` VARCHAR(255) NOT NULL,
  `alamatPembeli` VARCHAR(255) NOT NULL,
  `telpPembeli` VARCHAR(255) NOT NULL,
  `jumlahBarang` VARCHAR(255) NOT NULL,
  `barang_idbarang` INT NOT NULL,
  `barang_kategori_idkategori` INT NOT NULL,
  PRIMARY KEY (`idpembelian`, `barang_idbarang`, `barang_kategori_idkategori`))
ENGINE = InnoDB;

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
