/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myPanel;

import Main.AddFrame;
import Main.Config;
import Main.EditFrame;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import Main.pinDataset;
import java.awt.Color;
import java.awt.Font;
import java.awt.Frame;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.JTableHeader;

/**
 *
 * @author hp
 */
public class panel2 extends javax.swing.JPanel {

    private void load_table() {
        // membuat tampilan model tabel
        DefaultTableModel model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
//        model.setRowCount(0);

        model.addColumn("pKey");
        model.addColumn("No");
        model.addColumn("Nama");
        model.addColumn("Katgegori");
        model.addColumn("Jumlah");
        model.addColumn("Harga");
        model.addColumn("Harga Beli");
        model.addColumn("isDeleted");
        model.addColumn("idkategori");

        //menampilkan data database kedalam tabel
        try {
            int no = 1;
            String sql = "select idbarang,namaBarang,stockBarang,hargajualBarang,hargabeliBarang,namaKategori,isDeleted,idkategori "
                    + "from barang,kategori "
                    + "where kategori_idkategori = idkategori and isDeleted = 0;";

            java.sql.Connection conn = (Connection) Config.configDB();
            java.sql.Statement stm = conn.createStatement();
            java.sql.ResultSet res = stm.executeQuery(sql);

            while (res.next()) {

                model.addRow(new Object[]{res.getInt(1), no++, res.getString(2), res.getString(6), res.getInt(3), res.getInt(4), res.getInt(7), res.getInt(8)});
            }
            jTable1.setModel(model);
            jTable1.removeColumn(jTable1.getColumnModel().getColumn(8));
            jTable1.removeColumn(jTable1.getColumnModel().getColumn(7));
            jTable1.removeColumn(jTable1.getColumnModel().getColumn(6));
            jTable1.removeColumn(jTable1.getColumnModel().getColumn(0));
            
            Font font = new Font("Tahoma", Font.PLAIN, 20);
            JTableHeader header = jTable1.getTableHeader();
            header.setReorderingAllowed(false);
            header.setFont(font);
            
            jTable1.getTableHeader().setResizingAllowed(false);
            jTable1.setAutoResizeMode(JTable.AUTO_RESIZE_ALL_COLUMNS);
            jTable1.getColumnModel().getColumn(0).setPreferredWidth(1);
            jTable1.getColumnModel().getColumn(1).setPreferredWidth(400);
            jTable1.getColumnModel().getColumn(2).setPreferredWidth(100);
            jTable1.getColumnModel().getColumn(3).setPreferredWidth(70);
            jTable1.getColumnModel().getColumn(4).setPreferredWidth(90);
            
            jTable1.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
            jTable1.setSelectionBackground(new java.awt.Color(255, 120, 0));
            jTable1.setSelectionForeground(new java.awt.Color(255, 255, 255));
//            model.fireTableDataChanged();

        } catch (Exception e) {
            Logger.getLogger(AddFrame.class.getName()).log(Level.SEVERE, null, e);
        }
    }

    /**
     * Creates new form panel2
     */
    public panel2() {
        initComponents();
        if (pinDataset.isPegawai) {
            addButton2.setVisible(false);
            editButton2.setVisible(false);
            deleteButton2.setVisible(false);
            
        }
        load_table();
        
//        pinButton2.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        deleteButton2 = new javax.swing.JButton();
        editButton2 = new javax.swing.JButton();
        addButton2 = new javax.swing.JButton();
        pinButton2 = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 153, 153));
        setLayout(new java.awt.GridBagLayout());

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setGridColor(new java.awt.Color(255, 255, 51));
        jTable1.setRowHeight(50);
        jTable1.setSelectionBackground(new java.awt.Color(255, 97, 0));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setHeaderValue("Title 1");
            jTable1.getColumnModel().getColumn(1).setHeaderValue("Title 2");
            jTable1.getColumnModel().getColumn(2).setHeaderValue("Title 3");
            jTable1.getColumnModel().getColumn(3).setHeaderValue("Title 4");
        }

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 450;
        gridBagConstraints.ipady = 25;
        add(jScrollPane1, gridBagConstraints);

        deleteButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\JavaApplication2\\icons8-question-mark-32.png")); // NOI18N
        deleteButton2.setText("Delete");
        deleteButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteButton2MouseClicked(evt);
            }
        });
        deleteButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 0);
        add(deleteButton2, gridBagConstraints);

        editButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\JavaApplication2\\icons8-question-mark-32.png")); // NOI18N
        editButton2.setText("Edit");
        editButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editButton2MouseClicked(evt);
            }
        });
        editButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 115);
        add(editButton2, gridBagConstraints);

        addButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\JavaApplication2\\icons8-question-mark-32.png")); // NOI18N
        addButton2.setText("Add");
        addButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addButton2MouseClicked(evt);
            }
        });
        addButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 0, 215);
        add(addButton2, gridBagConstraints);

        pinButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\hp\\Documents\\JavaApplication2\\icons8-question-mark-32.png")); // NOI18N
        pinButton2.setText("Pin");
        pinButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pinButton2MouseClicked(evt);
            }
        });
        pinButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pinButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(10, 20, 0, 0);
        add(pinButton2, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked

    }//GEN-LAST:event_jTable1MouseClicked

    private void deleteButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButton2ActionPerformed

    }//GEN-LAST:event_deleteButton2ActionPerformed

    private void deleteButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteButton2MouseClicked
//        int col = jTable1.getColumnModel().getColumnIndexAtX(evt.getX());
//        int row = evt.getY()/jTable1.getRowHeight();
        int selectedrow = jTable1.getSelectedRow();
        //jTable1.addNotify();
        int pkey = (int) jTable1.getModel().getValueAt(selectedrow, 0);

        int a = JOptionPane.showConfirmDialog(null, " HAPUS ? ",
                "MESSAGE", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);

        if (a == JOptionPane.YES_OPTION) {
//            ((DefaultTableModel) jTable1.getModel()).removeRow(selectedrow);
            java.sql.Connection conn;
            String sql = "UPDATE barang SET isDeleted = 1 WHERE idbarang = "+ pkey +";";
            try {
                conn = (Connection) Config.configDB();
                java.sql.Statement stm = conn.createStatement();
                stm.executeUpdate(sql);
            } catch (SQLException ex) {
                
            }
            JOptionPane.showMessageDialog(null, "Data Berhasil Dihapus", "Warning", JOptionPane.WARNING_MESSAGE);
        }

        load_table();
    }//GEN-LAST:event_deleteButton2MouseClicked

    private void pinButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pinButton2ActionPerformed
        int selectedrow = jTable1.getSelectedRow();
//        int controw = jTable1.getRowCount() - 1;
//        int countcol = jTable1.getColumnCount() - 1;
        Object[] taskAsArray = new Object[]{
            jTable1.getModel().getValueAt(selectedrow, 0),
            jTable1.getModel().getValueAt(selectedrow, 2),
            jTable1.getModel().getValueAt(selectedrow, 3),
            jTable1.getModel().getValueAt(selectedrow, 4),
            jTable1.getModel().getValueAt(selectedrow, 5),
            jTable1.getModel().getValueAt(selectedrow, 6),
            jTable1.getModel().getValueAt(selectedrow, 7)};
        taskAsArray[3] = 0;
        pinDataset.setData(taskAsArray);
//        JOptionPane.showMessageDialog(null, pinDataset.getRowValue(0));
    }//GEN-LAST:event_pinButton2ActionPerformed

    private void pinButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pinButton2MouseClicked

    }//GEN-LAST:event_pinButton2MouseClicked

    private void addButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addButton2MouseClicked
//        new AddFrame().show();
        Frame fm = new AddFrame();
        fm.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                load_table();
            }
        });
        fm.show();
//        load_table();
    }//GEN-LAST:event_addButton2MouseClicked

    private void editButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButton2MouseClicked
//        int selectedrow = jTable1.getSelectedRow();
////        int controw = jTable1.getRowCount() - 1;
////        int countcol = jTable1.getColumnCount() - 1;
//        Object[] taskAsArray = new Object[]{
//            jTable1.getModel().getValueAt(selectedrow, 0),
//            jTable1.getModel().getValueAt(selectedrow, 2),
//            jTable1.getModel().getValueAt(selectedrow, 3),
//            jTable1.getModel().getValueAt(selectedrow, 4)};
//        pinDataset.setEditData(taskAsArray);
//        new EditFrame().show();
    }//GEN-LAST:event_editButton2MouseClicked

    private void addButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addButton2ActionPerformed

    private void editButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editButton2ActionPerformed
                int selectedrow = jTable1.getSelectedRow();
//        int controw = jTable1.getRowCount() - 1;
//        int countcol = jTable1.getColumnCount() - 1;
        Object[] taskAsArray = new Object[]{
            jTable1.getModel().getValueAt(selectedrow, 0),
            jTable1.getModel().getValueAt(selectedrow, 2),
            jTable1.getModel().getValueAt(selectedrow, 3),
            jTable1.getModel().getValueAt(selectedrow, 4)};
        pinDataset.setEditData(taskAsArray);
        Frame fm = new EditFrame();
        fm.addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosed(WindowEvent e) {
                load_table();
            }
        });
        fm.show();
    }//GEN-LAST:event_editButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton2;
    private javax.swing.JButton deleteButton2;
    private javax.swing.JButton editButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton pinButton2;
    // End of variables declaration//GEN-END:variables
}

